import { GoogleGenAI } from "@google/genai";

// Initialize the API client
// Ideally, in a production environment, this should be proxied through a backend to hide the key.
// For this frontend-only demo, we assume the environment variable is injected safely.
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Converts a base64 string (with data URI scheme) to a raw base64 string and mime type.
 */
const parseBase64 = (dataUrl: string) => {
  const matches = dataUrl.match(/^data:(.+);base64,(.+)$/);
  if (!matches || matches.length !== 3) {
    throw new Error('Invalid input image format.');
  }
  return {
    mimeType: matches[1],
    data: matches[2],
  };
};

/**
 * Generates a new image based on the input image and hairstyle description.
 */
export const changeHairstyle = async (
  originalImageBase64: string,
  hairstyleDescription: string
): Promise<string> => {
  try {
    const { mimeType, data } = parseBase64(originalImageBase64);

    // Prompt engineering to ensure the model focuses on hair editing while preserving the face.
    const prompt = `Change the person's hairstyle in this image to: ${hairstyleDescription}. Maintain the original face, lighting, and background as much as possible. High quality, realistic photo.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: prompt,
          },
          {
            inlineData: {
              data: data,
              mimeType: mimeType,
            },
          },
        ],
      },
    });

    // Extract the image from the response
    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          const base64EncodeString = part.inlineData.data;
          return `data:image/png;base64,${base64EncodeString}`;
        }
      }
    }

    throw new Error("No image was generated by the model.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};